name: "AniSearch"
guid: "776d9158-b91f-49d9-82c5-dacce63d63b8"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-anisearch.png"
version: "5"
targetAbi: "10.7.7.0"
framework: "net6.0"
owner: "jellyfin"
overview: "AniSearch metadata provider"
description: >
  AniSearch metadata provider

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.AniSearch.dll"
changelog: |2-
  ### Code or Repo Maintenance ###
  - Use meta ci (#13) @crobibero

  ### CI & build changes ###
  - Use meta ci (#13) @crobibero
